import type { Metadata } from 'next';
import RootLayout from './layout';

export const metadata: Metadata = {
  title: 'Kick Expert',
  description: 'Generated by create next app',
};

export default function ServerLayout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}